import * as SQLite from 'expo-sqlite';
import { randomUUID } from 'expo-crypto';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type EvidenceDraft = { localUri?: string; fileUrl: string; evidenceType: string; latitude: number; longitude: number; capturedAt: string; fileHash?: string };
export type ChecklistResponse = { checklistItemId: string; observedValue?: string; passed: boolean; remarks?: string };
export type PendingInspection = { clientSyncId: string; assignmentId: string; result: 'PASS' | 'FAIL'; remarks: string; failureReason?: string; checklistResults: ChecklistResponse[]; evidence: EvidenceDraft[]; startedAt?: string; completedAt?: string; syncState: 'PENDING' | 'SYNCING' | 'SYNCED' | 'FAILED' };
let db: SQLite.SQLiteDatabase;
export const API_URL = process.env.EXPO_PUBLIC_API_URL || 'http://localhost:5000/api';
export async function initOfflineStore() { db = await SQLite.openDatabaseAsync('smartmetri.db'); await db.execAsync('CREATE TABLE IF NOT EXISTS inspection_queue (clientSyncId TEXT PRIMARY KEY, assignmentId TEXT NOT NULL, result TEXT NOT NULL, remarks TEXT NOT NULL, failureReason TEXT, syncState TEXT NOT NULL, payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS assignment_cache (id TEXT PRIMARY KEY, payload TEXT NOT NULL, cachedAt TEXT NOT NULL); CREATE TABLE IF NOT EXISTS checklist_cache (id TEXT PRIMARY KEY, payload TEXT NOT NULL, cachedAt TEXT NOT NULL)'); }
export async function cacheAssignments(assignments: unknown[]) { for (const assignment of assignments as { id?: string }[]) if (assignment.id) await db.runAsync('INSERT OR REPLACE INTO assignment_cache (id, payload, cachedAt) VALUES (?, ?, ?)', assignment.id, JSON.stringify(assignment), new Date().toISOString()); }
export async function getCachedAssignments<T>(): Promise<T[]> { const rows = await db.getAllAsync<{ payload: string }>('SELECT payload FROM assignment_cache ORDER BY cachedAt DESC'); return rows.map(row => JSON.parse(row.payload) as T); }
export async function cacheChecklist(items: unknown[]) { for (const item of items as { id?: string }[]) if (item.id) await db.runAsync('INSERT OR REPLACE INTO checklist_cache (id, payload, cachedAt) VALUES (?, ?, ?)', item.id, JSON.stringify(item), new Date().toISOString()); }
export async function getCachedChecklist<T>(): Promise<T[]> { const rows = await db.getAllAsync<{ payload: string }>('SELECT payload FROM checklist_cache ORDER BY cachedAt DESC'); return rows.map(row => JSON.parse(row.payload) as T); }
export async function completeInspection(input: Omit<PendingInspection, 'clientSyncId' | 'syncState'>) { const completedAt = input.completedAt || new Date().toISOString(); const item: PendingInspection = { ...input, completedAt, clientSyncId: randomUUID(), syncState: 'PENDING' }; const location = item.evidence[0] || { latitude: 0, longitude: 0 }; await db.runAsync('INSERT INTO inspection_queue (clientSyncId, assignmentId, result, remarks, failureReason, syncState, payload) VALUES (?, ?, ?, ?, ?, ?, ?)', item.clientSyncId, item.assignmentId, item.result, item.remarks, item.failureReason || null, item.syncState, JSON.stringify({ ...item, latitude: location.latitude, longitude: location.longitude, startedAt: item.startedAt || completedAt, completedAt })); }
export async function getPendingInspections(): Promise<PendingInspection[]> { const rows = await db.getAllAsync<any>('SELECT clientSyncId, assignmentId, result, remarks, failureReason, syncState FROM inspection_queue WHERE syncState != ?', 'SYNCED'); return rows; }
export async function syncPendingInspections() { const token = await AsyncStorage.getItem('token'); const rows = await db.getAllAsync<any>('SELECT * FROM inspection_queue WHERE syncState IN (?, ?)', 'PENDING', 'FAILED'); for (const row of rows) { await db.runAsync('UPDATE inspection_queue SET syncState = ? WHERE clientSyncId = ?', 'SYNCING', row.clientSyncId); try { const payload = JSON.parse(row.payload); const form = new FormData(); const evidence = payload.evidence || []; form.append('payload', JSON.stringify(payload)); for (const item of evidence) if (item.localUri) form.append('evidence', { uri: item.localUri, name: `${payload.clientSyncId}-${evidence.indexOf(item)}.jpg`, type: 'image/jpeg' } as any); const response = await fetch(`${API_URL}/inspections/sync`, { method: 'POST', headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: form }); if (!response.ok) throw new Error(await response.text()); await db.runAsync('UPDATE inspection_queue SET syncState = ? WHERE clientSyncId = ?', 'SYNCED', row.clientSyncId); } catch { await db.runAsync('UPDATE inspection_queue SET syncState = ? WHERE clientSyncId = ?', 'FAILED', row.clientSyncId); } } }
